name: 🚀 Deploy & Restart Docker

on:
  push:
    branches:
      - main   # starte bei jedem Push auf main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 📦 Upload project to server
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: code4energy.de
          REMOTE_USER: deploy
          REMOTE_PORT: 22
          SOURCE: ./
          TARGET: /home/fl0x23/code4energy/
          ARGS: "-az --no-times --no-perms --delete"
          EXCLUDE: ".git*,.github*,.vscode*,data/,*/data/,*.pyc,__pycache__/,**/__pycache__/**,.env,.env.*"

      - name: 🐳 Restart Docker containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: code4energy.de
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/fl0x23/code4energy
            echo "➡️ Pulling updates and rebuilding containers..."
            docker compose down
            docker compose build
            docker compose up -d
            echo "✅ Docker containers restarted successfully!"